# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GrafanaDups < Formula
  desc "Extract crossplane resources"
  homepage "https://github.com/DoodleScheduling/grafana-dups"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/DoodleScheduling/grafana-dups/releases/download/v0.0.1/grafana-dups_0.0.1_darwin_amd64.tar.gz"
      sha256 "0cb93e3af409aae2a68a17a34ae785ac3be030979a50d0cc87ab95447e355adc"

      def install
        bin.install "grafana-dups"
      end
    end
    on_arm do
      url "https://github.com/DoodleScheduling/grafana-dups/releases/download/v0.0.1/grafana-dups_0.0.1_darwin_arm64.tar.gz"
      sha256 "06d37218d692268c1fe3981c4dbce22d4e06202bb83e316f51bed0c4967b1f16"

      def install
        bin.install "grafana-dups"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DoodleScheduling/grafana-dups/releases/download/v0.0.1/grafana-dups_0.0.1_linux_amd64.tar.gz"
        sha256 "0bff98fd2d2815094b12cb6741ffc09eb3641323ee7a90523365fb1f3b964808"

        def install
          bin.install "grafana-dups"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DoodleScheduling/grafana-dups/releases/download/v0.0.1/grafana-dups_0.0.1_linux_arm64.tar.gz"
        sha256 "2a08002a2908d57a05fc33cf810c2378b39d932a5143158bf74832faff5c48be"

        def install
          bin.install "grafana-dups"
        end
      end
    end
  end

  test do
    system "#{bin}/grafana-dups -h"
  end
end
