# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GrafanaDups < Formula
  desc "Extract crossplane resources"
  homepage "https://github.com/DoodleScheduling/grafana-dups"
  version "0.0.3"

  on_macos do
    on_intel do
      url "https://github.com/DoodleScheduling/grafana-dups/releases/download/v0.0.3/grafana-dups_0.0.3_darwin_amd64.tar.gz"
      sha256 "1fc8f5adb0cc77994ebd866953dd9fbb994356060752dfdb3e98ff6c362f9d25"

      def install
        bin.install "grafana-dups"
      end
    end
    on_arm do
      url "https://github.com/DoodleScheduling/grafana-dups/releases/download/v0.0.3/grafana-dups_0.0.3_darwin_arm64.tar.gz"
      sha256 "86085897b2b8f79c3922dcac147f4c0962d02b84cce026dcc29a63ba0f966189"

      def install
        bin.install "grafana-dups"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DoodleScheduling/grafana-dups/releases/download/v0.0.3/grafana-dups_0.0.3_linux_amd64.tar.gz"
        sha256 "5e2518134e2102e0a5c14aee88132ca68a43eb76fc8246599935cc1028cb3758"

        def install
          bin.install "grafana-dups"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/DoodleScheduling/grafana-dups/releases/download/v0.0.3/grafana-dups_0.0.3_linux_arm64.tar.gz"
        sha256 "b24344ed8d33c6ad5a1352d247613bb45614a5f25c5f179fcae577ad8b3aef48"

        def install
          bin.install "grafana-dups"
        end
      end
    end
  end

  test do
    system "#{bin}/grafana-dups -h"
  end
end
